packages:
  - connector
  - modules/*

allowBuilds:
  react-native-enriched-markdown: true
  unrs-resolver: true
patchedDependencies:
  react-native-nitro-modules@0.35.9: patches/react-native-nitro-modules@0.35.9.patch
  react-native-screens@4.26.2: patches/react-native-screens@4.26.2.patch
